"""update tipe seminar

Revision ID: 5cb5ea5a74f9
Revises: 99e56b1f2fd5
Create Date: 2026-05-01 23:27:24.925735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5cb5ea5a74f9'
down_revision: Union[str, Sequence[str], None] = '99e56b1f2fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seminar', 'status',
               existing_type=mysql.ENUM('terjadwal', 'selesai', 'batal'),
               type_=sa.Enum('terjadwal', 'final', 'selesai', name='statusseminar'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seminar', 'status',
               existing_type=sa.Enum('terjadwal', 'final', 'selesai', name='statusseminar'),
               type_=mysql.ENUM('terjadwal', 'selesai', 'batal'),
               existing_nullable=True)
    # ### end Alembic commands ###
