"""update komponen

Revision ID: 99e56b1f2fd5
Revises: c509c53f0a30
Create Date: 2026-05-01 16:19:10.580287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '99e56b1f2fd5'
down_revision: Union[str, Sequence[str], None] = 'c509c53f0a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('komponen_nilai', sa.Column('bobot', sa.Integer(), nullable=True))
    op.drop_column('komponen_nilai', 'kode_komponen')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('komponen_nilai', sa.Column('kode_komponen', mysql.VARCHAR(length=2), nullable=True))
    op.drop_column('komponen_nilai', 'bobot')
    # ### end Alembic commands ###
