"""add sign for dosen

Revision ID: 9c961298787f
Revises: 5cb5ea5a74f9
Create Date: 2026-05-02 09:37:49.273793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c961298787f'
down_revision: Union[str, Sequence[str], None] = '5cb5ea5a74f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dosen', sa.Column('tandatangan', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dosen', 'tandatangan')
    # ### end Alembic commands ###
