"""update table

Revision ID: c509c53f0a30
Revises: 
Create Date: 2026-05-01 13:03:13.310683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c509c53f0a30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('komponen_nilai', sa.Column('urutan', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'komponen_nilai', ['urutan'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'komponen_nilai', type_='unique')
    op.drop_column('komponen_nilai', 'urutan')
    # ### end Alembic commands ###
